name: real
description: "Estate application replica"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/svgs/

  fonts:
    - family: euclid_circular_a
      fonts:
        - asset: assets/fonts/Euclid-Circular-A-Light.ttf
          weight: 300
        - asset: assets/fonts/Euclid-Circular-A-Light-Italic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Euclid-Circular-A-Italic.ttf
          weight: 400
        - asset: assets/fonts/Euclid-Circular-A-Regular.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Euclid-Circular-A-Medium.ttf
          weight: 500
        - asset: assets/fonts/Euclid-Circular-A-Medium-Italic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Euclid-Circular-A-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Euclid-Circular-A-SemiBold-Italic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Euclid-Circular-A-Bold.ttf
          weight: 700
        - asset: assets/fonts/Euclid-Circular-A-Bold-Italic.ttf
          style: italic
          weight: 700
